// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ck.rt1.model;

import com.ck.rt1.model.Exercise;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Exercise_Roo_Configurable {
    
    declare @type: Exercise: @Configurable;
    
}
