// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ck.rt1.model;

import com.ck.rt1.model.Stylesheet;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Stylesheet_Roo_Configurable {
    
    declare @type: Stylesheet: @Configurable;
    
}
